name: SEGA_Kit
description: "AIO tools for SEGA"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.13.0
  flutter_acrylic: ^1.1.0
  win32: any
  ffi: any
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  fluentui_system_icons: ^1.1.273
  path_provider: ^2.1.1
  path: any
  file_picker: ^10.3.8
  ini: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.2.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app.webp
    - assets/gitea.svg
    - assets/github.svg
    - assets/chusan.ini