name: segaio
description: "Tools for SEGA-related I/O, based on Dniel97-segatools"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.16.0
  flutter_acrylic: ^1.1.4
  win32: ^5.15.0
  ffi: ^2.1.0
  window_manager: ^0.5.2
  screen_retriever: ^0.2.2
  fluentui_system_icons: ^1.1.273
  path_provider: ^2.1.6
  path: ^1.9.0
  file_picker: ^11.0.2
  ini: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_svg: ^2.3.0
  cupertino_icons: ^1.0.9
  archive: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app.webp
    - assets/gitea.svg
    - assets/github.svg