import 'package:flutter/services.dart';

class VKLibrary {
  static final Map<int, int> flutterToWinVK = {
    LogicalKeyboardKey.backspace.keyId: 0x08,
    LogicalKeyboardKey.tab.keyId: 0x09,
    LogicalKeyboardKey.enter.keyId: 0x0D,
    LogicalKeyboardKey.capsLock.keyId: 0x14,
    LogicalKeyboardKey.escape.keyId: 0x1B,
    LogicalKeyboardKey.space.keyId: 0x20,
    LogicalKeyboardKey.pageUp.keyId: 0x21,
    LogicalKeyboardKey.pageDown.keyId: 0x22,
    LogicalKeyboardKey.end.keyId: 0x23,
    LogicalKeyboardKey.home.keyId: 0x24,
    LogicalKeyboardKey.arrowLeft.keyId: 0x25,
    LogicalKeyboardKey.arrowUp.keyId: 0x26,
    LogicalKeyboardKey.arrowRight.keyId: 0x27,
    LogicalKeyboardKey.arrowDown.keyId: 0x28,
    LogicalKeyboardKey.printScreen.keyId: 0x2C,
    LogicalKeyboardKey.insert.keyId: 0x2D,
    LogicalKeyboardKey.delete.keyId: 0x2E,
    LogicalKeyboardKey.metaLeft.keyId: 0x5B,
    LogicalKeyboardKey.metaRight.keyId: 0x5C,
    LogicalKeyboardKey.contextMenu.keyId: 0x5D,
    LogicalKeyboardKey.f1.keyId: 0x70,
    LogicalKeyboardKey.f2.keyId: 0x71,
    LogicalKeyboardKey.f3.keyId: 0x72,
    LogicalKeyboardKey.f4.keyId: 0x73,
    LogicalKeyboardKey.f5.keyId: 0x74,
    LogicalKeyboardKey.f6.keyId: 0x75,
    LogicalKeyboardKey.f7.keyId: 0x76,
    LogicalKeyboardKey.f8.keyId: 0x77,
    LogicalKeyboardKey.f9.keyId: 0x78,
    LogicalKeyboardKey.f10.keyId: 0x79,
    LogicalKeyboardKey.f11.keyId: 0x7A,
    LogicalKeyboardKey.f12.keyId: 0x7B,
    LogicalKeyboardKey.numLock.keyId: 0x90,
    LogicalKeyboardKey.scrollLock.keyId: 0x91,
    LogicalKeyboardKey.shiftLeft.keyId: 0xA0,
    LogicalKeyboardKey.shiftRight.keyId: 0xA1,
    LogicalKeyboardKey.controlLeft.keyId: 0xA2,
    LogicalKeyboardKey.controlRight.keyId: 0xA3,
    LogicalKeyboardKey.altLeft.keyId: 0xA4,
    LogicalKeyboardKey.altRight.keyId: 0xA5,
    LogicalKeyboardKey.audioVolumeMute.keyId: 0xAD,
    LogicalKeyboardKey.audioVolumeDown.keyId: 0xAE,
    LogicalKeyboardKey.audioVolumeUp.keyId: 0xAF,
    LogicalKeyboardKey.mediaTrackNext.keyId: 0xB0,
    LogicalKeyboardKey.mediaTrackPrevious.keyId: 0xB1,
    LogicalKeyboardKey.mediaStop.keyId: 0xB2,
    LogicalKeyboardKey.mediaPlayPause.keyId: 0xB3,
    LogicalKeyboardKey.semicolon.keyId: 0xBA,
    LogicalKeyboardKey.equal.keyId: 0xBB,
    LogicalKeyboardKey.comma.keyId: 0xBC,
    LogicalKeyboardKey.minus.keyId: 0xBD,
    LogicalKeyboardKey.period.keyId: 0xBE,
    LogicalKeyboardKey.slash.keyId: 0xBF,
    LogicalKeyboardKey.backquote.keyId: 0xC0,
    LogicalKeyboardKey.bracketLeft.keyId: 0xDB,
    LogicalKeyboardKey.backslash.keyId: 0xDC,
    LogicalKeyboardKey.bracketRight.keyId: 0xDD,
    LogicalKeyboardKey.quote.keyId: 0xDE,
    LogicalKeyboardKey.numpad0.keyId: 0x60,
    LogicalKeyboardKey.numpad1.keyId: 0x61,
    LogicalKeyboardKey.numpad2.keyId: 0x62,
    LogicalKeyboardKey.numpad3.keyId: 0x63,
    LogicalKeyboardKey.numpad4.keyId: 0x64,
    LogicalKeyboardKey.numpad5.keyId: 0x65,
    LogicalKeyboardKey.numpad6.keyId: 0x66,
    LogicalKeyboardKey.numpad7.keyId: 0x67,
    LogicalKeyboardKey.numpad8.keyId: 0x68,
    LogicalKeyboardKey.numpad9.keyId: 0x69,
    LogicalKeyboardKey.numpadMultiply.keyId: 0x6A,
    LogicalKeyboardKey.numpadAdd.keyId: 0x6B,
    LogicalKeyboardKey.numpadSubtract.keyId: 0x6D,
    LogicalKeyboardKey.numpadDecimal.keyId: 0x6E,
    LogicalKeyboardKey.numpadDivide.keyId: 0x6F,
  };

  static const Map<int, String> specialNames = {
    0x08: "Backspace",
    0x09: "Tab",
    0x0D: "Enter",
    0x14: "Caps Lock",
    0x1B: "Esc",
    0x20: "Space",
    0x21: "Page Up",
    0x22: "Page Down",
    0x23: "End",
    0x24: "Home",
    0x25: "Left",
    0x26: "Up",
    0x27: "Right",
    0x28: "Down",
    0x2C: "Print Screen",
    0x5B: "L-Win",
    0x5C: "R-Win",
    0x5D: "Menu Key",
    0x70: "F1",
    0x71: "F2",
    0x72: "F3",
    0x73: "F4",
    0x74: "F5",
    0x75: "F6",
    0x76: "F7",
    0x77: "F8",
    0x78: "F9",
    0x79: "F10",
    0x7A: "F11",
    0x7B: "F12",
    0xA0: "L-Shift",
    0xA1: "R-Shift",
    0xA2: "L-Ctrl",
    0xA3: "R-Ctrl",
    0xA4: "L-Alt",
    0xA5: "R-Alt",
    0xAD: "Mute",
    0xAE: "Vol Down",
    0xAF: "Vol Up",
    0xB0: "Next Track",
    0xB1: "Prev Track",
    0xB2: "Stop",
    0xB3: "Play/Pause",
    0xBA: "; :",
    0xBB: "= +",
    0xBC: ", <",
    0xBD: "- _",
    0xBE: ". >",
    0xBF: "/ ?",
    0xC0: "` ~",
    0xDB: "[ {",
    0xDC: "\\ |",
    0xDD: "] }",
    0xDE: "' \"",
  };
}